export const mockProducts = [
  {
    name: "Elegant Summer Dress",
    description: "Flowy midi dress perfect for summer occasions.",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&h=500&fit=crop"],
    category: "Fashion",
    categoryId: "1",
    stock: 15,
    featured: true,
    rating: 4.5,
    reviewCount: 127,
    brand: "StyleCo",
    colors: ["Navy Blue", "Black", "Rose Pink"],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "Cotton Blend",
    tags: ["Summer", "Casual", "Midi", "Flowy"],
    gender: "Women",
    ageGroup: "Adult",
    season: "Summer"
  },
  {
    name: "Running Sneakers",
    description: "Lightweight running shoes with advanced cushioning technology.",
    price: 129.99,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop"],
    category: "Footwear",
    categoryId: "2", 
    stock: 35,
    featured: true,
    rating: 4.7,
    reviewCount: 203,
    brand: "RunTech",
    colors: ["White/Blue", "Black", "Gray/Orange"],
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "12"],
    material: "Mesh/Synthetic",
    tags: ["Running", "Athletic", "Cushioned", "Breathable"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season"
  },
  {
    name: "Designer Sunglasses",
    description: "Polarized sunglasses with UV protection.",
    price: 199.99,
    images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&h=500&fit=crop"],
    category: "Accessories",
    categoryId: "3",
    stock: 25,
    featured: true,
    rating: 4.3,
    reviewCount: 89,
    brand: "LuxVision",
    colors: ["Black", "Tortoise", "Gold", "Silver"],
    sizes: ["One Size"],
    material: "Titanium/Glass",
    tags: ["Polarized", "UV Protection", "Designer", "Premium"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season"
  },
  {
    name: "Wireless Headphones",
    description: "Premium wireless headphones with noise cancellation.",
    price: 299.99,
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop"],
    category: "Electronics",
    categoryId: "4",
    stock: 25,
    featured: true,
    rating: 4.8,
    reviewCount: 342,
    brand: "AudioTech",
    colors: ["Black", "White", "Silver", "Rose Gold"],
    sizes: ["One Size"],
    material: "Premium Plastic/Metal",
    tags: ["Wireless", "Noise Cancelling", "Premium", "Bluetooth"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    batteryLife: "30 hours",
    connectivity: "Bluetooth 5.0",
    features: ["Active Noise Cancellation", "Quick Charge", "Voice Assistant"]
  },
  {
    name: "Luxury Throw Blanket",
    description: "Ultra-soft cashmere blend throw blanket.",
    price: 129.99,
    images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=500&fit=crop"],
    category: "Home & Living",
    categoryId: "5",
    stock: 22,
    featured: true,
    rating: 4.6,
    reviewCount: 156,
    brand: "CozyHome",
    colors: ["Cream", "Gray", "Navy", "Burgundy"],
    sizes: ["50x60 inches", "60x80 inches"],
    material: "Cashmere Blend",
    tags: ["Luxury", "Soft", "Warm", "Premium"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    careInstructions: "Dry Clean Only",
    roomType: ["Living Room", "Bedroom"]
  },
  {
    name: "Smart Water Bottle",
    description: "Insulated smart water bottle that tracks hydration.",
    price: 99.99,
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&h=500&fit=crop"],
    category: "Sports & Fitness",
    categoryId: "6",
    stock: 28,
    featured: true
  },
  {
    name: "Hydrating Face Serum",
    description: "Intensive hydrating serum with hyaluronic acid.",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&h=500&fit=crop"],
    category: "Beauty & Care", 
    categoryId: "7",
    stock: 40,
    featured: true
  },
  {
    name: "Leather Bound Journal",
    description: "Handcrafted leather journal with lined pages.",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&h=500&fit=crop"],
    category: "Books & Media",
    categoryId: "8",
    stock: 20,
    featured: false
  },

  // Additional Fashion Items (categoryId: "1")
  {
    name: "Cozy Knit Sweater",
    description: "Soft merino wool sweater with ribbed details. Perfect for layering during cooler months.",
    price: 119.99,
    images: ["https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500&h=500&fit=crop"],
    category: "Fashion",
    categoryId: "1",
    stock: 20,
    featured: false
  },
  {
    name: "High-Waisted Jeans",
    description: "Classic high-waisted denim jeans with a modern fit. Made from sustainable denim.",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500&h=500&fit=crop"],
    category: "Fashion",
    categoryId: "1",
    stock: 35,
    featured: false
  },
  {
    name: "Silk Blouse",
    description: "Luxurious silk blouse with mother-of-pearl buttons. Perfect for professional occasions.",
    price: 149.99,
    images: ["https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=500&h=500&fit=crop"],
    category: "Fashion",
    categoryId: "1",
    stock: 12,
    featured: true,
    rating: 4.4,
    reviewCount: 112,
    brand: "ElegantWear",
    colors: ["White", "Cream", "Blush Pink", "Light Blue"],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "100% Silk",
    tags: ["Luxury", "Professional", "Elegant", "Premium"],
    gender: "Women",
    ageGroup: "Adult",
    season: "All Season",
    fit: "Regular",
    neckline: "V-Neck",
    sleeves: "Long Sleeve"
  },
  {
    name: "Leather Jacket",
    description: "Genuine leather jacket with classic design, perfect for any season.",
    price: 299.99,
    images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&h=500&fit=crop"],
    category: "Fashion",
    categoryId: "1",
    stock: 15,
    featured: true,
    rating: 4.7,
    reviewCount: 234,
    brand: "LeatherCraft",
    colors: ["Black", "Brown", "Navy", "Tan"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    material: "Genuine Leather",
    tags: ["Classic", "Durable", "Versatile", "Premium"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    fit: "Regular",
    lining: "Polyester",
    closure: "Zipper"
  },
  {
    name: "Cotton Polo Shirt",
    description: "Premium cotton polo shirt available in multiple colors.",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=500&h=500&fit=crop"],
    category: "Fashion",
    categoryId: "1",
    stock: 40,
    featured: false,
    rating: 4.2,
    reviewCount: 187,
    brand: "CasualFit",
    colors: ["White", "Navy", "Black", "Gray", "Red", "Green"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    material: "100% Cotton",
    tags: ["Casual", "Comfortable", "Breathable", "Classic"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "Spring/Summer",
    fit: "Regular",
    neckline: "Polo Collar",
    sleeves: "Short Sleeve"
  },

  // Additional Footwear Items (categoryId: "2")
  {
    name: "Formal Dress Shoes",
    description: "Classic leather dress shoes perfect for business and formal occasions.",
    price: 199.99,
    images: ["https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=500&h=500&fit=crop"],
    category: "Footwear",
    categoryId: "2",
    stock: 20,
    featured: false,
    rating: 4.5,
    reviewCount: 145,
    brand: "FormalStep",
    colors: ["Black", "Brown", "Burgundy"],
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"],
    material: "Genuine Leather",
    tags: ["Formal", "Business", "Classic", "Professional"],
    gender: "Men",
    ageGroup: "Adult",
    season: "All Season",
    heelHeight: "1 inch",
    toeStyle: "Round Toe",
    closure: "Lace-up"
  },
  {
    name: "Casual Boots",
    description: "Versatile ankle boots suitable for casual and semi-formal wear.",
    price: 159.99,
    images: ["https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=500&h=500&fit=crop"],
    category: "Footwear",
    categoryId: "2",
    stock: 25,
    featured: false,
    rating: 4.3,
    reviewCount: 167,
    brand: "UrbanWalk",
    colors: ["Brown", "Black", "Tan", "Gray"],
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"],
    material: "Leather Upper",
    tags: ["Casual", "Versatile", "Ankle", "Comfortable"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "Fall/Winter",
    heelHeight: "1.5 inches",
    toeStyle: "Round Toe",
    closure: "Lace-up"
  },
  {
    name: "Canvas Sneakers",
    description: "Classic canvas sneakers with rubber soles. Comfortable for daily wear.",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500&h=500&fit=crop"],
    category: "Footwear",
    categoryId: "2",
    stock: 45,
    featured: false,
    rating: 4.1,
    reviewCount: 289,
    brand: "CanvasCore",
    colors: ["White", "Black", "Red", "Navy", "Gray", "Pink"],
    sizes: ["6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"],
    material: "Canvas Upper",
    tags: ["Classic", "Casual", "Comfortable", "Daily Wear"],
    gender: "Unisex",
    ageGroup: "All Ages",
    season: "All Season",
    heelHeight: "0.5 inches",
    toeStyle: "Round Toe",
    closure: "Lace-up"
  },
  {
    name: "High Heels",
    description: "Elegant stiletto heels perfect for special occasions and formal events.",
    price: 179.99,
    images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&h=500&fit=crop"],
    category: "Footwear",
    categoryId: "2",
    stock: 18,
    featured: false,
    rating: 4.6,
    reviewCount: 132,
    brand: "ElegantStep",
    colors: ["Black", "Red", "Nude", "Silver"],
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10"],
    material: "Patent Leather",
    tags: ["Elegant", "Formal", "Stiletto", "Special Occasion"],
    gender: "Women",
    ageGroup: "Adult",
    season: "All Season",
    heelHeight: "4 inches",
    toeStyle: "Pointed Toe",
    closure: "Slip-on"
  },

  // Additional Accessories Items (categoryId: "3")
  {
    name: "Minimalist Leather Wallet",
    description: "Slim leather wallet with RFID blocking technology. Holds up to 8 cards and cash.",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop"],
    category: "Accessories",
    categoryId: "3",
    stock: 30,
    featured: false,
    rating: 4.5,
    reviewCount: 198,
    brand: "SlimCraft",
    colors: ["Black", "Brown", "Tan", "Navy"],
    material: "Genuine Leather",
    tags: ["Minimalist", "RFID Blocking", "Slim", "Premium"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    capacity: "8 Cards + Cash",
    features: ["RFID Blocking", "Slim Design", "Premium Stitching"],
    dimensions: "4.3 x 3.1 x 0.3 inches"
  },
  {
    name: "Silk Scarf",
    description: "Luxurious silk scarf with hand-painted floral design. Perfect accent piece.",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1515327479755-93fa0b1c0df2?w=500&h=500&fit=crop"],
    category: "Accessories",
    categoryId: "3",
    stock: 18,
    featured: false,
    rating: 4.7,
    reviewCount: 89,
    brand: "ArtisanSilk",
    colors: ["Floral Blue", "Rose Garden", "Autumn Leaves", "Classic Black"],
    sizes: ["35x35 inches"],
    material: "100% Silk",
    tags: ["Luxury", "Hand-painted", "Floral", "Accent"],
    gender: "Women",
    ageGroup: "Adult",
    season: "All Season",
    pattern: "Hand-painted Floral",
    careInstructions: "Dry Clean Only"
  },
  {
    name: "Designer Handbag",
    description: "Elegant leather handbag with gold hardware and multiple compartments.",
    price: 399.99,
    images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&h=500&fit=crop"],
    category: "Accessories",
    categoryId: "3",
    stock: 8,
    featured: true,
    rating: 4.8,
    reviewCount: 156,
    brand: "LuxeDesign",
    colors: ["Black", "Brown", "Burgundy", "Cream"],
    sizes: ["Medium", "Large"],
    material: "Italian Leather",
    tags: ["Designer", "Luxury", "Elegant", "Premium"],
    gender: "Women",
    ageGroup: "Adult",
    season: "All Season",
    hardware: "Gold",
    compartments: "Multiple",
    closure: "Magnetic Snap",
    dimensions: "12 x 9 x 5 inches"
  },
  {
    name: "Classic Watch",
    description: "Timeless analog watch with leather strap and water resistance.",
    price: 249.99,
    images: ["https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=500&h=500&fit=crop"],
    category: "Accessories",
    categoryId: "3",
    stock: 15,
    featured: false,
    rating: 4.6,
    reviewCount: 223,
    brand: "TimeClassic",
    colors: ["Black Strap", "Brown Strap", "Navy Strap"],
    sizes: ["38mm", "42mm"],
    material: "Stainless Steel Case, Leather Strap",
    tags: ["Classic", "Timeless", "Water Resistant", "Analog"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    waterResistance: "50m",
    movement: "Quartz",
    features: ["Date Display", "Luminous Hands", "Scratch Resistant"]
  },

  // Additional Electronics Items (categoryId: "4")
  {
    name: "Smart Fitness Watch",
    description: "Advanced fitness tracker with heart rate monitoring, GPS, and 7-day battery life.",
    price: 249.99,
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop"],
    category: "Electronics",
    categoryId: "4",
    stock: 30,
    featured: false,
    rating: 4.4,
    reviewCount: 312,
    brand: "FitTech",
    colors: ["Black", "White", "Blue", "Pink"],
    sizes: ["38mm", "42mm", "46mm"],
    material: "Aluminum Case, Silicone Band",
    tags: ["Fitness", "Smart", "GPS", "Heart Rate"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    batteryLife: "7 days",
    waterResistance: "5ATM",
    connectivity: ["Bluetooth", "Wi-Fi", "GPS"],
    features: ["Heart Rate Monitor", "Sleep Tracking", "Step Counter", "Workout Modes"]
  },
  {
    name: "Wireless Charging Pad",
    description: "Fast wireless charging pad compatible with all Qi-enabled devices. LED indicators included.",
    price: 39.99,
    images: ["https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=500&h=500&fit=crop"],
    category: "Electronics",
    categoryId: "4",
    stock: 50,
    featured: false,
    rating: 4.2,
    reviewCount: 167,
    brand: "ChargeTech",
    colors: ["Black", "White", "Silver"],
    material: "Tempered Glass Top, Aluminum Base",
    tags: ["Wireless", "Fast Charging", "Qi Compatible", "LED"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    chargingSpeed: "15W Fast Charge",
    compatibility: ["iPhone", "Samsung", "All Qi Devices"],
    features: ["LED Indicators", "Over-Temperature Protection", "Foreign Object Detection"],
    dimensions: "4 x 4 x 0.4 inches"
  },
  {
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with 360-degree sound and waterproof design.",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&h=500&fit=crop"],
    category: "Electronics",
    categoryId: "4",
    stock: 22,
    featured: false,
    rating: 4.5,
    reviewCount: 289,
    brand: "SoundWave",
    colors: ["Black", "Blue", "Red", "Gray"],
    material: "Fabric Mesh, Rubberized Body",
    tags: ["Portable", "360-degree Sound", "Waterproof", "Bass"],
    gender: "Unisex",
    ageGroup: "All Ages",
    season: "All Season",
    batteryLife: "12 hours",
    waterResistance: "IPX7",
    connectivity: ["Bluetooth 5.0", "AUX Input"],
    features: ["360-degree Sound", "Deep Bass", "Voice Assistant", "Speakerphone"]
  },
  {
    name: "Gaming Mechanical Keyboard",
    description: "RGB backlit mechanical keyboard with blue switches, perfect for gaming.",
    price: 149.99,
    images: ["https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=500&h=500&fit=crop"],
    category: "Electronics",
    categoryId: "4",
    stock: 35,
    featured: false,
    rating: 4.7,
    reviewCount: 456,
    brand: "GameTech",
    colors: ["Black", "White", "Gray"],
    material: "Aluminum Frame, ABS Keycaps",
    tags: ["Gaming", "Mechanical", "RGB", "Blue Switches"],
    gender: "Unisex",
    ageGroup: "Teen/Adult",
    season: "All Season",
    switchType: "Blue Mechanical",
    connectivity: ["USB-C", "Wireless 2.4GHz"],
    features: ["RGB Backlighting", "Anti-Ghosting", "Programmable Keys", "Gaming Mode"],
    layout: "Full Size (104 Keys)"
  },
  {
    name: "4K Webcam",
    description: "Ultra HD webcam with auto-focus and noise-canceling microphone for professional calls.",
    price: 199.99,
    images: ["https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=500&h=500&fit=crop"],
    category: "Electronics",
    categoryId: "4",
    stock: 18,
    featured: true,
    rating: 4.6,
    reviewCount: 234,
    brand: "ViewTech",
    colors: ["Black"],
    material: "Aluminum Housing, Glass Lens",
    tags: ["4K", "Auto-focus", "Professional", "Noise-canceling"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    resolution: "4K Ultra HD (3840x2160)",
    connectivity: ["USB 3.0", "USB-C"],
    features: ["Auto-focus", "Noise-canceling Mic", "Low Light Correction", "Privacy Shutter"],
    compatibility: ["Windows", "Mac", "Linux"]
  },

  // Additional Home & Living Items (categoryId: "5")
  {
    name: "Minimalist Table Lamp",
    description: "Modern LED table lamp with touch controls and adjustable brightness.",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop"],
    category: "Home & Living",
    categoryId: "5",
    stock: 25,
    featured: false,
    rating: 4.4,
    reviewCount: 178,
    brand: "ModernLight",
    colors: ["White", "Black", "Brass", "Silver"],
    sizes: ["Small (12 inches)", "Medium (16 inches)"],
    material: "Metal Base, Fabric Shade",
    tags: ["Minimalist", "LED", "Touch Control", "Adjustable"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    lightType: "LED",
    features: ["Touch Controls", "Dimmable", "Energy Efficient"],
    roomType: ["Bedroom", "Living Room", "Office"]
  },
  {
    name: "Ceramic Plant Pot Set",
    description: "Set of 3 handcrafted ceramic pots with drainage saucers and modern design.",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=500&h=500&fit=crop"],
    category: "Home & Living",
    categoryId: "5",
    stock: 18,
    featured: false,
    rating: 4.3,
    reviewCount: 145,
    brand: "GreenSpace",
    colors: ["White", "Terracotta", "Gray", "Black"],
    sizes: ["Small Set (4-6 inches)", "Large Set (6-8 inches)"],
    material: "Handcrafted Ceramic",
    tags: ["Handcrafted", "Drainage", "Modern", "Plant Care"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    features: ["Drainage Holes", "Matching Saucers", "Food Safe Glaze"],
    roomType: ["Living Room", "Kitchen", "Patio", "Office"],
    plantTypes: ["Small Plants", "Succulents", "Herbs"]
  },
  {
    name: "Aromatherapy Diffuser",
    description: "Ultrasonic essential oil diffuser with LED color-changing lights and timer settings.",
    price: 59.99,
    images: ["https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=500&fit=crop"],
    category: "Home & Living",
    categoryId: "5",
    stock: 30,
    featured: false,
    rating: 4.5,
    reviewCount: 267,
    brand: "AromaZen",
    colors: ["White", "Wood Grain", "Black"],
    sizes: ["100ml", "300ml", "500ml"],
    material: "BPA-Free Plastic, Wood Accent",
    tags: ["Aromatherapy", "Ultrasonic", "LED Lights", "Timer"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    capacity: "300ml",
    features: ["7 LED Colors", "Timer Settings", "Auto Shut-off", "Whisper Quiet"],
    roomType: ["Bedroom", "Living Room", "Office", "Spa"],
    runTime: "6-8 hours"
  },
  {
    name: "Smart Home Hub",
    description: "Voice-controlled smart home hub with built-in speaker and display.",
    price: 179.99,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&h=500&fit=crop"],
    category: "Home & Living",
    categoryId: "5",
    stock: 25,
    featured: false,
    rating: 4.6,
    reviewCount: 189,
    brand: "SmartHome",
    colors: ["Charcoal", "White", "Gray"],
    sizes: ["Standard"],
    material: "Fabric Mesh, Plastic Housing",
    tags: ["Smart", "Voice Control", "Speaker", "Display"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    display: "7-inch Touch Screen",
    connectivity: ["Wi-Fi", "Bluetooth", "Zigbee", "Thread"],
    features: ["Voice Assistant", "Smart Home Control", "Video Calling", "Music Streaming"],
    compatibility: ["Alexa", "Google Assistant", "Apple HomeKit"]
  },
  {
    name: "Memory Foam Pillow",
    description: "Ergonomic memory foam pillow for better sleep and neck support.",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=500&fit=crop"],
    category: "Home & Living",
    categoryId: "5",
    stock: 35,
    featured: false,
    rating: 4.7,
    reviewCount: 234,
    brand: "SleepWell",
    colors: ["White"],
    sizes: ["Standard", "Queen", "King"],
    material: "Memory Foam, Bamboo Cover",
    tags: ["Ergonomic", "Memory Foam", "Neck Support", "Sleep"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    firmness: "Medium",
    features: ["Cooling Gel", "Hypoallergenic", "Removable Cover", "CertiPUR-US Certified"],
    sleepPosition: ["Side Sleeper", "Back Sleeper"],
    careInstructions: "Machine Washable Cover"
  },

  // Additional Sports & Fitness Items (categoryId: "6")
  {
    name: "Yoga Mat Premium",
    description: "High-quality non-slip yoga mat with alignment lines. Made from eco-friendly materials.",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&h=500&fit=crop"],
    category: "Sports & Fitness",
    categoryId: "6",
    stock: 45,
    featured: false,
    rating: 4.6,
    reviewCount: 234,
    brand: "ZenFit",
    colors: ["Purple", "Blue", "Pink", "Black", "Green"],
    sizes: ["Standard (68x24 inches)", "Extra Long (72x24 inches)"],
    material: "TPE Eco-Friendly Material",
    tags: ["Yoga", "Non-slip", "Eco-friendly", "Alignment"],
    gender: "Unisex",
    ageGroup: "Adult",
    season: "All Season",
    thickness: "6mm",
    features: ["Alignment Lines", "Non-slip Surface", "Eco-friendly", "Easy to Clean"],
    activities: ["Yoga", "Pilates", "Meditation", "Stretching"]
  },
  {
    name: "Resistance Bands Set",
    description: "Complete set of resistance bands with different resistance levels and door anchor.",
    price: 29.99,
    images: ["https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=500&fit=crop"],
    category: "Sports & Fitness",
    categoryId: "6",
    stock: 60,
    featured: false
  },
  {
    name: "Adjustable Dumbbells",
    description: "Space-saving adjustable dumbbells with quick-change weight system.",
    price: 199.99,
    images: ["https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=500&fit=crop"],
    category: "Sports & Fitness",
    categoryId: "6",
    stock: 15,
    featured: true
  },
  {
    name: "Running Belt",
    description: "Lightweight running belt with multiple pockets for phone, keys, and essentials.",
    price: 24.99,
    images: ["https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=500&fit=crop"],
    category: "Sports & Fitness",
    categoryId: "6",
    stock: 35,
    featured: false
  },

  // Additional Beauty & Care Items (categoryId: "7")
  {
    name: "Organic Face Mask Set",
    description: "Set of 4 organic face masks for different skin concerns. Made with natural ingredients.",
    price: 39.99,
    images: ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500&h=500&fit=crop"],
    category: "Beauty & Care",
    categoryId: "7",
    stock: 25,
    featured: false
  },
  {
    name: "Premium Makeup Brush Set",
    description: "Professional 12-piece makeup brush set with synthetic bristles and rose gold handles.",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=500&h=500&fit=crop"],
    category: "Beauty & Care",
    categoryId: "7",
    stock: 35,
    featured: false
  },
  {
    name: "Anti-Aging Night Cream",
    description: "Premium night cream with retinol and hyaluronic acid for youthful skin.",
    price: 129.99,
    images: ["https://images.unsplash.com/photo-1570194065650-d99edd0ac16d?w=500&h=500&fit=crop"],
    category: "Beauty & Care",
    categoryId: "7",
    stock: 30,
    featured: true
  },
  {
    name: "Natural Lip Balm Set",
    description: "Set of 3 organic lip balms with different flavors and SPF protection.",
    price: 24.99,
    images: ["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=500&h=500&fit=crop"],
    category: "Beauty & Care",
    categoryId: "7",
    stock: 60,
    featured: false
  },

  // Additional Books & Media Items (categoryId: "8")
  {
    name: "Fountain Pen Set",
    description: "Elegant fountain pen set with refillable ink cartridges and premium gift box.",
    price: 129.99,
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=500&h=500&fit=crop"],
    category: "Books & Media",
    categoryId: "8",
    stock: 15,
    featured: false
  },
  {
    name: "Premium Notebook Collection",
    description: "Set of 3 premium lined notebooks with hardcover and elastic closure.",
    price: 34.99,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&h=500&fit=crop"],
    category: "Books & Media",
    categoryId: "8",
    stock: 25,
    featured: false
  },
  {
    name: "Desk Organizer Set",
    description: "Bamboo desk organizer with compartments for pens, paper clips, and stationery.",
    price: 45.99,
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&h=500&fit=crop"],
    category: "Books & Media",
    categoryId: "8",
    stock: 30,
    featured: false
  }
]

export const mockCategories = [
  {
    id: "1",
    name: "Fashion",
    description: "Trendy clothing and apparel for all occasions",
    image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&h=400&fit=crop"
  },
  {
    id: "2", 
    name: "Footwear",
    description: "Comfortable and stylish shoes for every step",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&h=400&fit=crop"
  },
  {
    id: "3",
    name: "Accessories", 
    description: "Complete your look with premium accessories",
    image: "https://images.unsplash.com/photo-1506629905069-5bc0f2f09ea8?w=600&h=400&fit=crop"
  },
  {
    id: "4",
    name: "Electronics",
    description: "Latest tech gadgets and devices", 
    image: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=600&h=400&fit=crop"
  },
  {
    id: "5",
    name: "Home & Living",
    description: "Stylish home essentials and decor",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=400&fit=crop"
  },
  {
    id: "6",
    name: "Sports & Fitness",
    description: "Active lifestyle gear and equipment",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=400&fit=crop"
  },
  {
    id: "7", 
    name: "Beauty & Care",
    description: "Premium beauty and personal care products",
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&h=400&fit=crop"
  },
  {
    id: "8",
    name: "Books & Media", 
    description: "Books, magazines, and entertainment media",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&h=400&fit=crop"
  }
]

export const mockTeamMembers = [
  {
    name: "Sarah Johnson",
    role: "CEO & Founder",
    image: "https://images.unsplash.com/photo-1494790108755-2616b612c341?w=300&h=300&fit=crop&crop=face",
    bio: "Passionate about creating beautiful, sustainable fashion for everyone."
  },
  {
    name: "Michael Chen", 
    role: "Head of Design",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop&crop=face",
    bio: "Award-winning designer with 15 years of experience in luxury fashion."
  },
  {
    name: "Emily Rodriguez",
    role: "Operations Manager",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=300&fit=crop&crop=face",
    bio: "Ensures every order is perfect and delivered with care."
  }
]